name: Update

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:    

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:

      - name: Update README Timestamp
        run: |
          git clone --depth 1 https://$TOKEN@github.com/NidinaKoirala/iam-tech-freak.git
          cd ${GITHUB_WORKSPACE}/iam-tech-freak
          echo "Last updated on $(date)" > update.txt
          git config user.name "Nidina Koirala"
          git config user.email "nidinakoirala1112@gmail.com"
          git add update.txt
          git commit -m "Auto-update timestamp: $(date)"
          git push origin main
